export const manualAliases: Record<string, string[]> = {
  "1. Playwright Fundamentals": ["playwright fundamentals"],
  "2. Installation & Commands": ["playwright install", "installation"],
  "3. Test Structure & Hooks": ["test structure", "hooks", "test hooks"],
  "4. Locators": ["locators", "locator"],
  "5. Actions": ["actions"],
  "6. Assertions": ["web-first assertions", "auto-retrying assertions"],
  "7. Auto-Waiting": ["auto-waiting", "auto-wait", "auto wait", "autowaiting", "actionability"],
  "8. Browser / Context / Page": ["browser context", "browsercontext", "browser contexts", "browsercontexts"],
  "9. Fixtures": ["fixtures", "fixture"],
  "10. Configuration": ["playwright config", "playwright.config", "config file"],
  "11. Projects": ["projects", "project"],
  "12. Authentication": ["authentication", "storage state", "storagestate", "storage states"],
  "13. API Testing": ["api testing", "api tests", "request fixture", "api request context"],
  "14. Network Mocking": ["network mocking", "mock network", "route interception", "intercept"],
  "15. Frames": ["frames", "frame", "frame locator", "framelocator", "iframes", "iframe"],
  "16. Dialogs": ["dialogs", "dialog"],
  "17. Uploads & Downloads": ["uploads", "downloads", "upload", "download"],
  "18. Screenshots / Videos": ["screenshots", "videos", "screenshot", "video"],
  "19. Debugging": ["debug", "debugging"],
  "20. Trace Viewer": ["trace viewer", "trace", "traces", "trace viewer"],
  "21. UI Mode & Codegen": ["ui mode", "codegen"],
  "22. Parallelism & Workers": ["parallelism", "workers", "worker", "parallel", "sharding", "shard", "shards"],
  "23. Test Isolation": ["test isolation", "isolation"],
  "24. Retries & Timeouts": ["retries", "retry", "timeouts", "timeout"],
  "25. Page Object Model": ["page object model", "page objects", "pom"],
  "26. CI/CD": ["ci/cd", "ci", "cd", "github actions", "github actions workflow"],
  "27. Best Practices Checklist": ["best practices", "best practice"],
  "28. Common Playwright Mistakes": ["common mistakes"],
  "29. Important Comparisons": ["important comparisons"],
  "30. Interview Questions": ["interview questions"],
  "31. Core API Cheat Sheet": ["cheat sheet"],
  "32. Official Docs Index": ["official docs"],
};
